version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: my-mongodb
    ports:
      - "127.0.0.1:27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: debugduck
      MONGO_INITDB_ROOT_PASSWORD: duckduckgo
    command: ["--bind_ip", "127.0.0.1"]

  flask-app:
    image: your-flask-app-image:latest
    container_name: my-flask-app
    ports:
      - "80:80"
    depends_on:
      - mongodb
    environment:
      MONGODB_URI: mongodb://debugduck:duckduckgo@mongodb:27017/your_db_name
    networks:
      - my-network

networks:
  my-network:
    driver: bridge

volumes:
  mongodb_data:
