version: '3'
services:
  flask-app:
    build:
      context: . # Aqui você especifica o caminho para o Dockerfile que construirá a imagem do seu aplicativo Flask.
      dockerfile: Dockerfile  # Substitua pelo nome correto do seu Dockerfile Flask, se necessário.
    ports:
      - "80:80"  # Mapeia a porta 80 do host para a porta 80 do contêiner.
    depends_on:
      - mongodb  # Indica que este serviço depende dos serviços 'mongodb' e 'mysql'.
    environment:
      MONGO_URI: mongodb://mongodb:27017/ARduck  # Configura as variáveis de ambiente para a aplicação Flask.
    networks:
      - minha-rede

  mongodb:
    image: mongo  # Usa a imagem oficial do MongoDB do Docker Hub.
    ports:
      - "27017:27017"  # Mapeia a porta 27017 para acessar o MongoDB no contêiner.
    volumes:
      - mongodb_data:/data/db  # Define um volume chamado 'mongodb_data' para persistir os dados do MongoDB.
    networks:
      - minha-rede

volumes:
  mongodb_data:  # Define o volume 'mongodb_data' usado pelo serviço MongoDB.

networks:
  minha-rede: