version: '3.3'

services:
  mongodb:
    image: mongo:latest
    container_name: my-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: debugduck
      MONGO_INITDB_ROOT_PASSWORD: duckduckgo

  flask-app:
    build:
      context: .
    container_name: my-flask-app
    ports:
      - "80:80"
    links:
      - mongodb
    environment:
      MONGODB_URI: mongodb://debugduck:duckduckgo@mongodb:27017

volumes:
  mongodb_data:
